### PR TITLE
Make Issue.body a (String | None)

### PR DESCRIPTION
**Pull request by mfelsche**
The issue body can be null. E.g. for issue: https://github.com/ponylang/rfcs/issues/197
This failed in extracting data from the json response.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
Your example link is coming back a 404 for me

**Comment by SeanTAllen** [comment]
190 in that repo is a PR and has a different type in this library. Did you mean a different number?

**Comment by SeanTAllen** [comment]
The custom ponyc compilation change is unrelated. Please remove from the PR.

**Comment by mfelsche** [comment]
The link is fixed. It is a PR, but the behaviour is similar for issues.

FYI: The github openapi spec lists this field as nullable: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml#L42858 I found the official docs to be quite unprecise sometimes.

**Comment by SeanTAllen** [comment]
See #4 @mfelsche. I'm thinking in the case of body that "" as a default rather than None would be better for ergonomics without impacting on actual usage with GH. Can we discuss the correct approach more there or on Zulip?

**Comment by SeanTAllen** [comment]
I changed my mind on this and decided that yes @mfelsche, you had the correct idea in the beginning. 

Joe and I discussed during sync and agreed that this is the right way to address for now as we are doing this at a very low-level and that if we had a higher-level API that setting "" as the default for null on a String could make sense.

**Pull request merged**
